const TWITTER_TOKENS = {
    TWITTER_CONSUMER_KEY: "ZJFUHbZQWSIqxc7gcQOjUen0Y",
    TWITTER_CONSUMER_SECRET: "6wJbtuEaBDAitB7exJz6lvEEMaOp5gPUMkLVWGAkcC3x9XkwcI",
    TWITTER_ACCESS_TOKEN: "633651630-lcEswWQpkJMVpn3oKKebsSTSIQGtD4D8zclQpHn5",
    TWITTER_TOKEN_SECRET: "Bfl6FSaprkNOZjVBdVral2nsajkCklYsqQA5L4RGcTarK"
};